alter table ONE2ONETEST_PERSON add constraint FK_ONE2ONETEST_PERSON_ON_PASSPORT foreign key (PASSPORT_ID) references ONE2ONETEST_PASSPORT(ID);
create index IDX_ONE2ONETEST_PERSON_ON_PASSPORT on ONE2ONETEST_PERSON (PASSPORT_ID);
